name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install tools
      run: sudo apt-get install -y docker.io
    - name: build
      run: docker run -v $PWD:/data ubuntu:19.10 sh -c "apt-get install -y libavcodec58 libavfilter7 libavformat58 libavutil56 libspdlog-dev && cd /data && cmake . && make -j"
    - name: release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: libVideoShowFileNamePlugin.so
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
