name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install tools
      run: sudo apt-get install -y yasm 
    - name: clone kplayer pkg
      run: git clone https://github.com/bytelang/plugin-pkg.git
    - name: complie spdlog
      run: git clone https://github.com/gabime/spdlog.git && cd spdlog && cmake . && make -j && sudo make install 
    - name: complie ffmpeg
      run: git clone https://git.ffmpeg.org/ffmpeg.git --depth=1 && cd ffmpeg && ./configure && make -j && sudo make install 
    - name: configure
      run: cmake .
    - name: make
      run: make
    - name: release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: libVideoShowFileNamePlugin.so
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
